"""
Dashboard suggestion engine.

This module translates market structure + group summary + macro trade bias
into a public-safe dashboard-level interpretation.

It does NOT calculate allocation percentage.
It does NOT expose private alpha parameters.
It does NOT expose private position sizing rules.
It does NOT replace the market structure engine.

Purpose:
- Keep market structure classification separate from dashboard interpretation.
- Provide a clean explanation layer for dashboard / Power BI / demo output.
- Keep final allocation logic in a later allocation engine.
"""


# ============================================================
# 1. Public-safe suggestion labels
# ============================================================

DASHBOARD_SUGGESTION_LABELS = {
    "risk_on_growth": (
        "Growth leadership active; "
        "use continuation / pullback confirmation"
    ),
    "ai_leadership": (
        "AI leadership active; "
        "monitor AI-Core and AI-Broad continuation quality"
    ),
    "risk_on_hedged": (
        "Risk-on leadership exists, but hedge strength is also active; "
        "use staged exposure"
    ),
    "commodity_hedge": (
        "Commodity / hedge leadership strongest"
    ),
    "defensive_reduce": (
        "Defensive mixed structure; reduce exposure and wait for confirmation"
    ),
    "risk_off": (
        "Risk-off confirmed; prioritize capital protection"
    ),
    "mixed_risk_on_hedge": (
        "Partial risk-on leadership with hedge strength; wait for confirmation"
    ),
    "defensive_rotation": (
        "Defensive sector rotation active; avoid aggressive growth exposure"
    ),
    "mixed_wait": (
        "Mixed structure; wait for clearer leadership"
    ),
}


# ============================================================
# 2. Helper functions
# ============================================================

def get_bias(group_summary, group_name):
    """
    Read group bias from group_summary.

    Expected group_summary format:
        {
            "Growth": {"green_count": 2, "red_count": 6, "bias": "Weaker"},
            "AI-Core": {"green_count": 2, "red_count": 1, "bias": "Stronger"},
            ...
        }
    """

    return group_summary.get(group_name, {}).get("bias", "Mixed")


def is_stronger(group_summary, group_name):
    """
    Check whether a group is stronger.
    """

    return get_bias(group_summary, group_name) == "Stronger"


def is_weaker(group_summary, group_name):
    """
    Check whether a group is weaker.
    """

    return get_bias(group_summary, group_name) == "Weaker"


# ============================================================
# 3. Main dashboard suggestion function
# ============================================================

def generate_dashboard_suggestion(
    market_structure,
    group_summary,
    macro_trade_bias=None,
    selected_asset=None,
):
    """
    Generate a public-safe dashboard suggestion.

    Inputs:
        market_structure:
            Output label from the market structure engine.

        group_summary:
            Group breadth summary generated by the market structure engine.

        macro_trade_bias:
            Optional macro trade bias text from the macro / regime layer.

        selected_asset:
            Optional selected asset name from a later asset-strength layer.
            Keep this optional so the suggestion engine does not depend on
            allocation or private symbol-level logic.

    Output:
        A dashboard-level suggestion string.

    Boundary:
        This function does not calculate allocation percentage.
        This function does not generate final trade orders.
        This function does not determine stop loss, take profit, or trailing rules.
    """

    if not market_structure:
        return DASHBOARD_SUGGESTION_LABELS["mixed_wait"]

    macro_text = macro_trade_bias or ""

    growth_strong = is_stronger(group_summary, "Growth")
    risk_off_strong = is_stronger(group_summary, "Risk-off")
    commodity_strong = is_stronger(group_summary, "Commodity")
    sector_strong = is_stronger(group_summary, "Sector")

    growth_weak = is_weaker(group_summary, "Growth")

    # --------------------------------------------------------
    # 1. True risk-off
    # --------------------------------------------------------
    if "Risk-off" in market_structure:
        return DASHBOARD_SUGGESTION_LABELS["risk_off"]

    # --------------------------------------------------------
    # 2. Clean growth leadership
    # --------------------------------------------------------
    if "Risk-on Growth Leadership" in market_structure:
        if selected_asset:
            return (
                f"{selected_asset} leadership active; "
                "use continuation / pullback confirmation"
            )
        return DASHBOARD_SUGGESTION_LABELS["risk_on_growth"]

    # --------------------------------------------------------
    # 3. AI leadership
    # --------------------------------------------------------
    if "AI Leadership" in market_structure:
        if selected_asset:
            return (
                f"{selected_asset} AI leadership active; "
                "monitor continuation quality"
            )
        return DASHBOARD_SUGGESTION_LABELS["ai_leadership"]

    # --------------------------------------------------------
    # 4. Risk-on but hedged
    # --------------------------------------------------------
    if "Risk-on / Hedged" in market_structure:
        if "Reduced exposure" in macro_text:
            return (
                "Risk-on leadership exists, "
                "but macro bias suggests reduced exposure"
            )
        return DASHBOARD_SUGGESTION_LABELS["risk_on_hedged"]

    # --------------------------------------------------------
    # 5. Commodity / inflation leadership
    # --------------------------------------------------------
    if "Commodity / Inflation Leadership" in market_structure:
        return DASHBOARD_SUGGESTION_LABELS["commodity_hedge"]

    # --------------------------------------------------------
    # 6. Defensive sector rotation
    # --------------------------------------------------------
    if "Defensive Sector Rotation" in market_structure:
        return DASHBOARD_SUGGESTION_LABELS["defensive_rotation"]

    # --------------------------------------------------------
    # 7. Mixed risk-on with hedge
    # --------------------------------------------------------
    if "Mixed / Risk-on with hedge" in market_structure:
        if selected_asset:
            return (
                f"{selected_asset} has partial leadership, "
                "but hedge strength requires staged exposure"
            )
        return DASHBOARD_SUGGESTION_LABELS["mixed_risk_on_hedge"]

    # --------------------------------------------------------
    # 8. Mixed defensive
    # --------------------------------------------------------
    if "Mixed / Defensive" in market_structure:
        if commodity_strong and not growth_strong:
            return DASHBOARD_SUGGESTION_LABELS["commodity_hedge"]

        if risk_off_strong and growth_weak:
            return DASHBOARD_SUGGESTION_LABELS["defensive_reduce"]

        if sector_strong and not growth_strong:
            return DASHBOARD_SUGGESTION_LABELS["defensive_rotation"]

        return DASHBOARD_SUGGESTION_LABELS["defensive_reduce"]

    # --------------------------------------------------------
    # 9. Fallback
    # --------------------------------------------------------
    return DASHBOARD_SUGGESTION_LABELS["mixed_wait"]